// swift-tools-version: 6.0
import PackageDescription

let swiftSettings: [SwiftSetting] = [
    .enableUpcomingFeature("ExistentialAny"),
    .enableUpcomingFeature("InternalImportsByDefault"),
    .enableExperimentalFeature("StrictConcurrency")
]

let package = Package(
    name: "swift-solana-kit",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [
        .library(name: "Kit", targets: ["Kit"]),
        .library(name: "SolanaErrors", targets: ["SolanaErrors"]),
        .library(name: "CodecsCore", targets: ["CodecsCore"]),
        .library(name: "Rpc", targets: ["Rpc"]),
        .library(name: "RpcGraphql", targets: ["RpcGraphql"])
    ],
    dependencies: [],
    targets: [
        .target(name: "SolanaErrors", dependencies: [], swiftSettings: swiftSettings),
        .target(name: "Assertions", dependencies: ["SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "NominalTypes", dependencies: [], swiftSettings: swiftSettings),
        .target(name: "CodecsCore", dependencies: ["SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "CodecsNumbers", dependencies: ["CodecsCore", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "CodecsStrings", dependencies: ["CodecsCore", "CodecsNumbers", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "CodecsDataStructures", dependencies: ["CodecsCore", "CodecsNumbers", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "FixedPoints", dependencies: ["CodecsCore", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Options", dependencies: ["CodecsCore", "CodecsDataStructures", "CodecsNumbers", "CodecsStrings", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Codecs", dependencies: ["CodecsCore", "CodecsDataStructures", "CodecsNumbers", "CodecsStrings", "FixedPoints", "Options"], swiftSettings: swiftSettings),
        .target(name: "FastStableStringify", dependencies: [], swiftSettings: swiftSettings),
        .target(name: "Functional", dependencies: [], swiftSettings: swiftSettings),
        .target(name: "Promises", dependencies: [], swiftSettings: swiftSettings),
        .target(name: "CryptoBackend", dependencies: ["SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "CryptoKitBackend", dependencies: ["CryptoBackend", "Curve25519Math", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Curve25519Math", dependencies: ["CryptoBackend", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Addresses", dependencies: ["Assertions", "CodecsCore", "CodecsStrings", "CryptoBackend", "NominalTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Keys", dependencies: ["Assertions", "CodecsCore", "CodecsStrings", "CryptoBackend", "NominalTypes", "Promises", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Instructions", dependencies: ["Addresses", "CodecsCore", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "RpcSpecTypes", dependencies: ["SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "RpcSpec", dependencies: ["Promises", "RpcSpecTypes", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .target(name: "RpcTypes", dependencies: ["Addresses", "CodecsCore", "CodecsNumbers", "CodecsStrings", "FixedPoints", "NominalTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "RpcTransformers", dependencies: ["Functional", "NominalTypes", "RpcSpecTypes", "RpcTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "RpcTransportHttp", dependencies: ["Promises", "RpcSpec", "RpcSpecTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "RpcParsedTypes", dependencies: ["Addresses", "RpcTypes"], swiftSettings: swiftSettings),
        .target(name: "Accounts", dependencies: ["Addresses", "CodecsCore", "CodecsStrings", "RpcSpec", "RpcTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "TransactionMessages", dependencies: ["Addresses", "CodecsCore", "CodecsDataStructures", "CodecsNumbers", "Functional", "Instructions", "NominalTypes", "RpcTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Transactions", dependencies: ["Addresses", "CodecsCore", "CodecsDataStructures", "CodecsNumbers", "CodecsStrings", "CryptoBackend", "Functional", "Instructions", "Keys", "NominalTypes", "RpcTypes", "SolanaErrors", "TransactionMessages"], swiftSettings: swiftSettings),
        .target(name: "OffchainMessages", dependencies: ["Addresses", "CodecsCore", "CodecsDataStructures", "CodecsNumbers", "CodecsStrings", "CryptoBackend", "Keys", "NominalTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Signers", dependencies: ["Addresses", "CodecsCore", "Instructions", "Keys", "NominalTypes", "OffchainMessages", "Promises", "SolanaErrors", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .target(name: "WalletAccountSigner", dependencies: ["Addresses", "CodecsCore", "Keys", "Promises", "Signers", "SolanaErrors", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .target(name: "RpcApi", dependencies: ["Addresses", "CodecsCore", "CodecsStrings", "Keys", "RpcParsedTypes", "RpcSpec", "RpcTransformers", "RpcTypes", "SolanaErrors", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .target(name: "Rpc", dependencies: ["FastStableStringify", "Functional", "RpcApi", "RpcSpec", "RpcSpecTypes", "RpcTransformers", "RpcTransportHttp", "RpcTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Subscribable", dependencies: ["Promises", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "RpcSubscriptionsSpec", dependencies: ["Promises", "RpcSpecTypes", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .target(name: "RpcSubscriptionsChannelWebsocket", dependencies: ["Functional", "RpcSubscriptionsSpec", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .target(name: "RpcSubscriptionsApi", dependencies: ["Addresses", "Keys", "RpcSubscriptionsSpec", "RpcTransformers", "RpcTypes", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .target(name: "RpcSubscriptions", dependencies: ["FastStableStringify", "Functional", "Promises", "RpcSpecTypes", "RpcSubscriptionsApi", "RpcSubscriptionsChannelWebsocket", "RpcSubscriptionsSpec", "RpcTransformers", "RpcTypes", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .target(name: "TransactionConfirmation", dependencies: ["Addresses", "CodecsStrings", "Keys", "Promises", "Rpc", "RpcSubscriptions", "RpcTypes", "SolanaErrors", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .target(name: "Sysvars", dependencies: ["Accounts", "CodecsCore", "CodecsDataStructures", "CodecsNumbers", "RpcTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "InstructionPlans", dependencies: ["Instructions", "Keys", "Promises", "SolanaErrors", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .target(name: "PluginCore", dependencies: [], swiftSettings: swiftSettings),
        .target(name: "PluginInterfaces", dependencies: ["Addresses", "InstructionPlans", "Keys", "RpcSpec", "RpcSubscriptionsSpec", "RpcTypes", "Signers"], swiftSettings: swiftSettings),
        .target(name: "ProgramClientCore", dependencies: ["Accounts", "Addresses", "CodecsCore", "InstructionPlans", "Instructions", "PluginInterfaces", "RpcApi", "Signers", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "Programs", dependencies: ["Addresses", "SolanaErrors"], swiftSettings: swiftSettings),
        .target(name: "RpcGraphql", dependencies: ["CodecsStrings", "FastStableStringify"], swiftSettings: swiftSettings),
        .target(name: "Kit", dependencies: ["Accounts", "Addresses", "Codecs", "Functional", "InstructionPlans", "Instructions", "Keys", "OffchainMessages", "PluginCore", "PluginInterfaces", "ProgramClientCore", "Programs", "Rpc", "RpcApi", "RpcParsedTypes", "RpcSpecTypes", "RpcSubscriptions", "RpcTypes", "Signers", "Subscribable", "Sysvars", "TransactionConfirmation", "TransactionMessages", "Transactions", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "SolanaErrorsTests", dependencies: ["SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "NominalTypesTests", dependencies: ["NominalTypes"], swiftSettings: swiftSettings),
        .testTarget(name: "AssertionsTests", dependencies: ["Assertions", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "CodecsCoreTests", dependencies: ["CodecsCore", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "CodecsNumbersTests", dependencies: ["CodecsCore", "CodecsNumbers", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "CodecsStringsTests", dependencies: ["CodecsCore", "CodecsNumbers", "CodecsStrings", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "CodecsDataStructuresTests", dependencies: ["CodecsCore", "CodecsNumbers", "CodecsStrings", "CodecsDataStructures", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "FixedPointsTests", dependencies: ["FixedPoints", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "OptionsTests", dependencies: ["CodecsCore", "CodecsNumbers", "CodecsStrings", "Options", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "CodecsTests", dependencies: ["Codecs"], swiftSettings: swiftSettings),
        .testTarget(name: "FastStableStringifyTests", dependencies: ["FastStableStringify"], swiftSettings: swiftSettings),
        .testTarget(name: "FunctionalTests", dependencies: ["Functional"], swiftSettings: swiftSettings),
        .testTarget(name: "PromisesTests", dependencies: ["Promises"], swiftSettings: swiftSettings),
        .testTarget(name: "SubscribableTests", dependencies: ["Promises", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .testTarget(name: "CryptoBackendTests", dependencies: ["CryptoBackend"], swiftSettings: swiftSettings),
        .testTarget(name: "Curve25519MathTests", dependencies: ["Curve25519Math", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "CryptoKitBackendTests", dependencies: ["CryptoBackend", "CryptoKitBackend"], swiftSettings: swiftSettings),
        .testTarget(name: "AddressesTests", dependencies: ["Addresses", "CryptoBackend", "CryptoKitBackend", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "InstructionsTests", dependencies: ["Addresses", "Instructions", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcSpecTypesTests", dependencies: ["RpcSpecTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcSpecTests", dependencies: ["Promises", "RpcSpec", "RpcSpecTypes"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcSubscriptionsSpecTests", dependencies: ["Promises", "RpcSpecTypes", "RpcSubscriptionsSpec", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcSubscriptionsChannelWebsocketTests", dependencies: ["Promises", "RpcSubscriptionsChannelWebsocket", "RpcSubscriptionsSpec", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcSubscriptionsApiTests", dependencies: ["Addresses", "Keys", "RpcSpecTypes", "RpcSubscriptionsApi", "RpcSubscriptionsSpec", "RpcTransformers", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcSubscriptionsTests", dependencies: ["Promises", "RpcSpecTypes", "RpcSubscriptions", "RpcSubscriptionsSpec", "RpcTypes", "SolanaErrors", "Subscribable"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcTypesTests", dependencies: ["Addresses", "CodecsCore", "RpcTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcParsedTypesTests", dependencies: ["Addresses", "RpcParsedTypes", "RpcTypes"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcTransformersTests", dependencies: ["RpcSpecTypes", "RpcTransformers", "RpcTypes", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcTransportHttpTests", dependencies: ["Promises", "RpcSpec", "RpcSpecTypes", "RpcTransportHttp", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcApiTests", dependencies: ["Addresses", "RpcApi", "RpcSpec", "RpcSpecTypes", "RpcTypes"], swiftSettings: swiftSettings),
        .testTarget(name: "RpcTests", dependencies: ["Addresses", "CodecsCore", "CodecsDataStructures", "CodecsNumbers", "CodecsStrings", "CryptoBackend", "CryptoKitBackend", "Curve25519Math", "FastStableStringify", "FixedPoints", "Functional", "Instructions", "Keys", "OffchainMessages", "Options", "Promises", "Rpc", "RpcSpec", "RpcSpecTypes", "RpcSubscriptions", "RpcSubscriptionsChannelWebsocket", "RpcSubscriptionsSpec", "RpcTypes", "Signers", "SolanaErrors", "Subscribable", "TransactionConfirmation", "TransactionMessages", "Transactions", "WalletAccountSigner"], swiftSettings: swiftSettings),
        .testTarget(name: "TransactionMessagesTests", dependencies: ["Addresses", "Instructions", "SolanaErrors", "TransactionMessages"], swiftSettings: swiftSettings),
        .testTarget(name: "TransactionsTests", dependencies: ["Addresses", "CryptoBackend", "CryptoKitBackend", "Instructions", "Keys", "SolanaErrors", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .testTarget(name: "TransactionConfirmationTests", dependencies: ["Addresses", "CodecsStrings", "Keys", "Promises", "RpcTypes", "SolanaErrors", "TransactionConfirmation", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .testTarget(name: "OffchainMessagesTests", dependencies: ["Addresses", "CryptoBackend", "Keys", "OffchainMessages", "SolanaErrors"], swiftSettings: swiftSettings),
        .testTarget(name: "SignersTests", dependencies: ["Addresses", "CryptoBackend", "CryptoKitBackend", "Instructions", "Keys", "OffchainMessages", "Promises", "Signers", "SolanaErrors", "TransactionMessages", "Transactions"], swiftSettings: swiftSettings),
        .testTarget(name: "WalletAccountSignerTests", dependencies: ["Addresses", "Keys", "Promises", "Signers", "SolanaErrors", "Transactions", "WalletAccountSigner"], swiftSettings: swiftSettings),
        .testTarget(name: "KeysTests", dependencies: ["CryptoBackend", "CryptoKitBackend", "Keys", "SolanaErrors"], swiftSettings: swiftSettings)
    ]
)
