name: Daily Integration
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch: {}
jobs:
  integration:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - run: swift build
      - run: swift test
